[main]
title = "introductory"
description = "introductory"
files = [
    "viz_earth_coordinates.py",
    "viz_morphing.py",
    "viz_slice.py",
    "viz_surfaces.py",
    "viz_arrow.py",
    "viz_gltf.py",
    "viz_picking.py",
    "viz_solar_system.py",
    "viz_texture.py",
    "viz_cone.py",
    "viz_gltf_animated.py",
    "viz_selection.py",
    "viz_sphere.py",
    "viz_timers.py",
    "viz_earth_animation.py",
    "viz_gltf_export.py",
    "viz_skinning.py",
    "viz_spiky.py"
]

[demos]
title = ""
description = ""
position = 1
enable = true
files = [
    "viz_advanced.py",
    "viz_fiber_odf.py",
    "viz_roi_contour.py",
    "viz_animated_surfaces.py",
    "viz_markers.py",
    "viz_tesseract.py",
    "collision-particles.py",
    "viz_fine_tuning_gl_context.py",
    "viz_network.py",
    "viz_brownian_motion.py",
    "viz_fractals.py",
    "viz_network_animated.py",
    "viz_bundles.py",
    "viz_pbr_interactive.py",
    "viz_emwave_animation.py",
    "viz_helical_motion.py",
    "viz_play_video.py"
]

[ui]
title = ""
description = ""
position = 4
enable = true
files = [
    "viz_check_boxes.py",
    "viz_drawpanel.py",
    "viz_radio_buttons.py",
    "viz_tab.py",
    "viz_ui_listbox.py",
    "viz_buttons.py",
    "viz_combobox.py",
    "viz_layout.py",
    "viz_shapes.py",
    "viz_ui.py",
    "viz_ui_slider.py"
]

[animation]
title = ""
description = ""
position = 7
enable = true
files = [
    "viz_interpolators.py",
    "viz_bezier_interpolator.py",
    "viz_introduction.py",
    "viz_camera.py",
    "viz_robot_arm_animation.py",
    "viz_color_interpolators.py",
    "viz_spline_interpolator.py",
    "viz_custom_interpolator.py",
    "viz_timeline.py",
    "viz_hierarchical_animation.py",
    "viz_using_time_equations.py"
]

[shaders]
title = ""
description = ""
position = 9
enable = true
files = [
    "viz_pbr_spheres.py",
    "viz_principled_spheres.py",
    "viz_sdf_cylinder.py",
    "viz_sdfactor.py",
    "viz_shader.py"
]

[pybullet]
title = ""
description = ""
position = 10
enable = true
files = [
    "viz_ball_collide.py",
    "viz_brick_wall.py",
    "viz_chain.py",
    "viz_domino.py",
    "viz_wrecking_ball.py"
]

[stream]
title = ""
description = ""
position = 13
enable = true
files = [
    "viz_interaction.py",
    "viz_no_interaction.py",
    "viz_widget.py"
]
